# Generated by Django 5.2.13 on 2026-04-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripeion',
            new_name='description',
        ),
    ]
